"""Comparison gallery - generate HTML galleries for before/after comparisons."""

import base64
import io
from pathlib import Path

import numpy as np
from PIL import Image


def generate_gallery(
    pairs: list[tuple[Path, Path]],
    output_path: Path,
    title: str = "Artefex Restoration Gallery",
) -> str:
    """Generate an HTML gallery comparing original and restored images.

    Args:
        pairs: List of (original_path, restored_path) tuples.
        output_path: Where to save the HTML file.
        title: Gallery title.

    Returns:
        Output path as string.
    """
    cards = ""
    for orig_path, rest_path in pairs:
        orig_b64 = _img_to_b64(orig_path)
        rest_b64 = _img_to_b64(rest_path)

        # Compute quick diff stats
        try:
            o = np.array(Image.open(orig_path).convert("RGB"), dtype=np.float64)
            r = np.array(Image.open(rest_path).convert("RGB"), dtype=np.float64)
            if o.shape != r.shape:
                r = np.array(Image.open(rest_path).convert("RGB").resize(
                    Image.open(orig_path).size, Image.LANCZOS
                ), dtype=np.float64)
            mse = float(np.mean((o - r) ** 2))
            psnr = 10 * np.log10(255.0**2 / mse) if mse > 0 else 999
            stats = f"PSNR: {psnr:.1f} dB"
        except Exception:
            stats = ""

        cards += f"""
        <div class="card">
            <div class="card-header">{orig_path.name} <span class="stats">{stats}</span></div>
            <div class="pair">
                <div class="img-box">
                    <div class="label">Original</div>
                    <img src="data:image/png;base64,{orig_b64}" alt="Original">
                </div>
                <div class="img-box">
                    <div class="label">Restored</div>
                    <img src="data:image/png;base64,{rest_b64}" alt="Restored">
                </div>
            </div>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ --bg:#0a0a0f; --surface:#12121a; --border:#1e1e2e; --text:#e0e0e8; --dim:#6b6b80; --accent:#7c6ff7; }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:'SF Mono','Cascadia Code',monospace; background:var(--bg); color:var(--text); padding:2rem; }}
  .container {{ max-width:1000px; margin:0 auto; }}
  h1 {{ font-size:1.5rem; background:linear-gradient(135deg,var(--accent),#a78bfa); -webkit-background-clip:text; -webkit-text-fill-color:transparent; margin-bottom:1.5rem; }}
  .card {{ background:var(--surface); border:1px solid var(--border); border-radius:8px; margin-bottom:1.5rem; overflow:hidden; }}
  .card-header {{ padding:0.75rem 1rem; border-bottom:1px solid var(--border); font-weight:600; font-size:0.85rem; display:flex; justify-content:space-between; }}
  .stats {{ color:var(--dim); font-weight:400; }}
  .pair {{ display:grid; grid-template-columns:1fr 1fr; }}
  .img-box {{ position:relative; }}
  .img-box img {{ width:100%; display:block; }}
  .label {{ position:absolute; top:0.5rem; left:0.5rem; background:rgba(0,0,0,0.7); color:var(--dim); font-size:0.65rem; padding:0.2rem 0.5rem; border-radius:3px; text-transform:uppercase; letter-spacing:0.05em; }}
  .footer {{ text-align:center; color:var(--dim); font-size:0.7rem; margin-top:2rem; }}
  @media(max-width:600px) {{ .pair {{ grid-template-columns:1fr; }} }}
</style>
</head>
<body>
<div class="container">
  <h1>{title}</h1>
  {cards}
  <div class="footer">Generated by Artefex - {len(pairs)} comparison(s)</div>
</div>
</body>
</html>"""

    output_path.write_text(html, encoding="utf-8")
    return str(output_path)


def _img_to_b64(path: Path) -> str:
    """Convert image to base64 thumbnail."""
    try:
        img = Image.open(path).convert("RGB")
        img.thumbnail((500, 500))
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return base64.b64encode(buf.getvalue()).decode()
    except Exception:
        return ""
