"""Model registry - manages neural model discovery, download, and loading."""

import hashlib
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

MODEL_DIR = Path.home() / ".artefex" / "models"

REGISTRY = {
    "deblock-v1": {
        "name": "FBCNN JPEG Deblocking",
        "description": "Flexible Blind CNN for JPEG artifact removal with QF-aware restoration (Apache 2.0)",
        "filename": "deblock_v1.onnx",
        "input_size": (256, 256),
        "channels": 3,
        "category": "compression",
        "version": "1.0.0",
        "sha256": "ef6cfa496f4a7dfbe56aa47b10bc5abf087ceabd54def0c72880bf10cc021899",
        "size_mb": 274.4,
    },
    "denoise-v1": {
        "name": "DnCNN Color Blind Denoiser",
        "description": "Blind RGB denoiser for Gaussian noise sigma 0-55 (KAIR, MIT)",
        "filename": "denoise_v1.onnx",
        "input_size": (256, 256),
        "channels": 3,
        "category": "noise",
        "version": "1.0.0",
        "sha256": "7ede32a06e448f00328b3d1aba48e648e1659b66bf39178685a9cc23ce20f32c",
        "size_mb": 2.6,
    },
    "sharpen-v1": {
        "name": "NAFNet GoPro Deblurring",
        "description": "Same-size detail recovery and deblurring (megvii-research, MIT)",
        "filename": "sharpen_v1.onnx",
        "input_size": (256, 256),
        "channels": 3,
        "category": "resolution",
        "version": "1.0.0",
        "sha256": "10b5ebb9de68e701fc4b3d2b9c810514b8aee603462b02cea506856a940554b5",
        "size_mb": 65.7,
    },
    "color-correct-v1": {
        "name": "Color Correction v1",
        "description": "Classical signal processing - no neural model available with permissive license",
        "filename": "color_correct_v1.onnx",
        "input_size": (256, 256),
        "channels": 3,
        "category": "color",
        "version": "1.0.0",
        "sha256": "",
        "size_mb": 0.0,
    },
    "inpaint-v1": {
        "name": "LaMa Inpainting",
        "description": "Large Mask Inpainting for repairing physical damage, scratches, tears (Apache 2.0, OpenCV)",
        "filename": "inpaint_v1.onnx",
        "input_size": (512, 512),
        "channels": 3,
        "category": "inpainting",
        "version": "1.0.0",
        "sha256": "",
        "size_mb": 88.3,
    },
    "aigen-detect-v1": {
        "name": "SAFE AI-Generated Image Detector",
        "description": "Binary real/synthetic classifier covering modern AI generators (Apache 2.0)",
        "filename": "aigen_detect_v1.onnx",
        "input_size": (256, 256),
        "channels": 3,
        "category": "detection",
        "version": "1.0.0",
        "sha256": "10fae056ede657b1a7937cfddaa8f71e41b3c79a4df2770f96a1f3134a7536bd",
        "size_mb": 5.5,
    },
}


@dataclass
class ModelInfo:
    key: str
    name: str
    description: str
    filename: str
    input_size: tuple[int, int]
    channels: int
    category: str
    version: str
    sha256: str = ""
    size_mb: float = 0.0
    local_path: Optional[Path] = None

    @property
    def is_available(self) -> bool:
        return self.local_path is not None and self.local_path.exists()

    @property
    def is_trained(self) -> bool:
        """Check if the model appears to be a real trained model (not a test stub).

        Test models generated by create_test_models.py are under 5 KB.
        Real trained U-Net models are typically 1-50 MB.
        """
        if not self.is_available:
            return False
        size_bytes = self.local_path.stat().st_size
        return size_bytes > 10_000  # 10 KB threshold


class ModelRegistry:
    """Discovers, manages, and loads neural models for restoration."""

    def __init__(self, model_dir: Path = MODEL_DIR):
        self.model_dir = model_dir
        self.model_dir.mkdir(parents=True, exist_ok=True)

    def _build_model_info(
        self, key: str, info: dict, local_path: Optional[Path] = None
    ) -> ModelInfo:
        """Build a ModelInfo from a registry entry."""
        if local_path is None:
            candidate = self.model_dir / info["filename"]
            local_path = candidate if candidate.exists() else None
        return ModelInfo(
            key=key,
            name=info["name"],
            description=info["description"],
            filename=info["filename"],
            input_size=tuple(info["input_size"]),
            channels=info["channels"],
            category=info["category"],
            version=info["version"],
            sha256=info.get("sha256", ""),
            size_mb=info.get("size_mb", 0.0),
            local_path=local_path,
        )

    def list_models(self) -> list[ModelInfo]:
        """List all known models and their availability."""
        return [
            self._build_model_info(key, info)
            for key, info in REGISTRY.items()
        ]

    def get_model(self, key: str) -> Optional[ModelInfo]:
        """Get info about a specific model."""
        if key not in REGISTRY:
            return None
        return self._build_model_info(key, REGISTRY[key])

    def get_model_for_category(self, category: str) -> Optional[ModelInfo]:
        """Find the best model for a degradation category."""
        for key, info in REGISTRY.items():
            if info["category"] == category:
                return self.get_model(key)
        return None

    def import_model(self, source_path: Path, key: str) -> ModelInfo:
        """Import a model file into the registry."""
        if key not in REGISTRY:
            raise ValueError(
                f"Unknown model key: {key}. "
                f"Known keys: {list(REGISTRY.keys())}"
            )

        info = REGISTRY[key]
        dest = self.model_dir / info["filename"]
        shutil.copy2(source_path, dest)

        return self._build_model_info(key, info, local_path=dest)

    def model_path(self, key: str) -> Optional[Path]:
        """Get the local path for a model, or None if not available."""
        model = self.get_model(key)
        if model and model.is_available:
            return model.local_path
        return None

    @staticmethod
    def _verify_sha256(path: Path, expected: str) -> bool:
        """Verify file SHA256 checksum. Returns True if valid."""
        h = hashlib.sha256()
        with open(path, "rb") as f:
            while True:
                chunk = f.read(8192)
                if not chunk:
                    break
                h.update(chunk)
        return h.hexdigest() == expected

    def download_model(
        self,
        key: str,
        url: Optional[str] = None,
        progress_callback: Optional[object] = None,
    ) -> ModelInfo:
        """Download a model by key.

        Args:
            key: Registry key for the model.
            url: Download URL. If None, the model must already exist
                locally or an error is raised.
            progress_callback: Optional callable(bytes_downloaded,
                total_bytes) invoked during download.

        Returns:
            ModelInfo with local_path set.

        Raises:
            ValueError: If the key is unknown.
            FileNotFoundError: If no URL and model is not local.
            RuntimeError: If checksum verification fails.
        """
        if key not in REGISTRY:
            raise ValueError(
                f"Unknown model key: {key}. "
                f"Known keys: {list(REGISTRY.keys())}"
            )

        info = REGISTRY[key]
        dest = self.model_dir / info["filename"]

        # Already downloaded - return immediately
        if dest.exists():
            return self._build_model_info(key, info, local_path=dest)

        if url is None:
            raise FileNotFoundError(
                f"Model '{key}' not found locally and no URL provided"
            )

        # Download with optional progress reporting
        import urllib.request

        tmp_path = dest.with_suffix(".part")
        try:
            req = urllib.request.urlopen(url)  # noqa: S310
            total = int(req.headers.get("Content-Length", 0))
            downloaded = 0

            with open(tmp_path, "wb") as out:
                while True:
                    chunk = req.read(65536)
                    if not chunk:
                        break
                    out.write(chunk)
                    downloaded += len(chunk)
                    if progress_callback is not None:
                        progress_callback(downloaded, total)

            # Verify checksum if one is configured
            expected_hash = info.get("sha256", "")
            if expected_hash and not self._verify_sha256(
                tmp_path, expected_hash
            ):
                tmp_path.unlink(missing_ok=True)
                raise RuntimeError(
                    f"SHA256 mismatch for model '{key}'. "
                    "The download may be corrupted."
                )

            shutil.move(str(tmp_path), str(dest))
        except Exception:
            tmp_path.unlink(missing_ok=True)
            raise

        return self._build_model_info(key, info, local_path=dest)

    def download_all(
        self,
        url_map: Optional[dict[str, str]] = None,
        progress_callback: Optional[object] = None,
    ) -> list[ModelInfo]:
        """Download all registered models.

        Args:
            url_map: Dict mapping model keys to download URLs.
                Keys without a URL are skipped if not already local.
            progress_callback: Optional callable(key, bytes_downloaded,
                total_bytes) invoked during each download.

        Returns:
            List of ModelInfo for successfully downloaded models.
        """
        if url_map is None:
            url_map = {}

        results: list[ModelInfo] = []
        for key in REGISTRY:
            url = url_map.get(key)
            dest = self.model_dir / REGISTRY[key]["filename"]

            # Skip models without a URL that are not already local
            if url is None and not dest.exists():
                continue

            def _wrapped_cb(downloaded: int, total: int) -> None:
                if progress_callback is not None:
                    progress_callback(key, downloaded, total)

            model_info = self.download_model(
                key,
                url=url,
                progress_callback=_wrapped_cb if progress_callback else None,
            )
            results.append(model_info)

        return results

    def generate_test_models(self) -> list[ModelInfo]:
        """Generate lightweight test ONNX models for all registry entries.

        Creates minimal Conv-ReLU-Conv models with a residual skip
        connection and random weights. Requires the onnx and numpy
        packages (optional dependencies).

        Returns:
            List of ModelInfo for all generated models.
        """
        import numpy as np
        import onnx
        from onnx import TensorProto, helper

        results: list[ModelInfo] = []

        for key, info in REGISTRY.items():
            channels = info["channels"]

            # -- Input --
            x = helper.make_tensor_value_info(
                "input", TensorProto.FLOAT,
                [1, channels, None, None],
            )

            # -- Conv1 weights (3x3, same channels) --
            w1_data = np.random.default_rng(42).standard_normal(
                (channels, channels, 3, 3)
            ).astype(np.float32) * 0.1
            w1 = helper.make_tensor(
                "conv1_w", TensorProto.FLOAT,
                [channels, channels, 3, 3],
                w1_data.flatten().tolist(),
            )

            # -- Conv2 weights (3x3, same channels) --
            w2_data = np.random.default_rng(43).standard_normal(
                (channels, channels, 3, 3)
            ).astype(np.float32) * 0.1
            w2 = helper.make_tensor(
                "conv2_w", TensorProto.FLOAT,
                [channels, channels, 3, 3],
                w2_data.flatten().tolist(),
            )

            # -- Graph nodes --
            conv1 = helper.make_node(
                "Conv", ["input", "conv1_w"], ["conv1_out"],
                pads=[1, 1, 1, 1],
            )
            relu = helper.make_node(
                "Relu", ["conv1_out"], ["relu_out"],
            )
            conv2 = helper.make_node(
                "Conv", ["relu_out", "conv2_w"], ["conv2_out"],
                pads=[1, 1, 1, 1],
            )
            # Residual skip connection
            add = helper.make_node(
                "Add", ["input", "conv2_out"], ["output"],
            )

            # -- Output --
            y = helper.make_tensor_value_info(
                "output", TensorProto.FLOAT,
                [1, channels, None, None],
            )

            graph = helper.make_graph(
                [conv1, relu, conv2, add],
                f"test_{key}",
                [x], [y],
                initializer=[w1, w2],
            )

            model = helper.make_model(
                graph, opset_imports=[helper.make_opsetid("", 13)]
            )
            # Keep generated test models compatible with older onnxruntime
            # versions used on CI runners.
            model.ir_version = 11
            onnx.checker.check_model(model)

            dest = self.model_dir / info["filename"]
            onnx.save(model, str(dest))

            results.append(
                self._build_model_info(key, info, local_path=dest)
            )

        return results
