"""Story generator - narrates an image's degradation history in natural language.

Takes analysis results and weaves them into a readable forensic narrative,
like a detective piecing together what happened to a crime scene photo.
"""

from pathlib import Path

from artefex.models import AnalysisResult, Degradation
from artefex.grade import compute_grade


def generate_story(file_path: Path, result: AnalysisResult) -> str:
    """Generate a natural language narrative of an image's history."""
    grade = compute_grade(result)
    lines = []

    name = file_path.name
    w, h = result.dimensions
    fmt = result.file_format

    # Opening
    lines.append(f'The file "{name}" is a {w}x{h} {fmt} image.')

    if not result.degradations:
        lines.append(
            "It appears to be in pristine condition with no detectable degradation. "
            "This image has either been well-preserved or was recently created."
        )
        return " ".join(lines)

    lines.append(
        f"After forensic analysis, Artefex has identified "
        f"{len(result.degradations)} issue(s) and assigned it a grade of "
        f"{grade['grade']} ({grade['score']}/100)."
    )
    lines.append("")

    # Reconstruct the story in estimated chronological order
    lines.append("Here is the estimated history of what happened to this image:")
    lines.append("")

    # Group by category for narrative flow
    provenance = [d for d in result.degradations if d.category == "provenance"]
    compression = [d for d in result.degradations if d.category == "compression"]
    quality = [d for d in result.degradations if d.category in ("noise", "resolution", "color")]
    artifacts = [d for d in result.degradations if d.category in ("artifact", "overlay")]
    metadata = [d for d in result.degradations if d.category == "metadata"]
    forgery = [d for d in result.degradations if d.category == "forgery"]
    security = [d for d in result.degradations if d.name in ("Steganography Detected",)]

    step = 1

    # Origin story
    device = next((d for d in provenance if d.name == "Device Identification"), None)
    if device:
        lines.append(f"{step}. {_narrate_device(device)}")
        step += 1

    ai_gen = next((d for d in provenance if d.name == "AI-Generated Content"), None)
    if ai_gen:
        lines.append(f"{step}. {_narrate_ai(ai_gen)}")
        step += 1

    # What happened to it
    for d in compression:
        lines.append(f"{step}. {_narrate_compression(d)}")
        step += 1

    for d in quality:
        lines.append(f"{step}. {_narrate_quality(d)}")
        step += 1

    for d in artifacts:
        lines.append(f"{step}. {_narrate_artifact(d)}")
        step += 1

    # Platform journey
    platform = next((d for d in provenance if d.name == "Platform Processing"), None)
    if platform:
        lines.append(f"{step}. {_narrate_platform(platform)}")
        step += 1

    # Metadata
    for d in metadata:
        lines.append(f"{step}. {_narrate_metadata(d)}")
        step += 1

    # Forgery
    for d in forgery:
        lines.append(f"{step}. {_narrate_forgery(d)}")
        step += 1

    # Security
    for d in security:
        lines.append(f"{step}. {_narrate_security(d)}")
        step += 1

    lines.append("")

    # Conclusion
    if grade["grade"] in ("A", "B"):
        lines.append(
            "Despite some minor issues, this image is in good shape overall. "
            "Restoration would yield marginal improvements."
        )
    elif grade["grade"] == "C":
        lines.append(
            "This image has been through some processing but is still usable. "
            "Restoration could noticeably improve its quality."
        )
    elif grade["grade"] == "D":
        lines.append(
            "This image has suffered significant degradation across multiple dimensions. "
            "Restoration is recommended to recover lost quality."
        )
    else:
        lines.append(
            "This image has been heavily degraded, likely through multiple rounds of "
            "processing, compression, and sharing. Full restoration is strongly recommended."
        )

    return "\n".join(lines)


def _narrate_device(d: Degradation) -> str:
    detail = d.detail.split(".")[0] if d.detail else "unknown device"
    return f"The image appears to have originated from a {detail.lower().replace('likely device: ', '')}."


def _narrate_ai(d: Degradation) -> str:
    conf = d.confidence
    if conf > 0.7:
        return "Strong indicators suggest this image was generated by an AI model rather than captured by a camera."
    elif conf > 0.5:
        return "There are moderate signs that this image may have been AI-generated, though this is not conclusive."
    return "Some statistical patterns hint at possible AI generation, but confidence is low."


def _narrate_compression(d: Degradation) -> str:
    if d.name == "JPEG Compression":
        if d.severity > 0.7:
            return "The image was saved as a JPEG with heavy compression, causing visible 8x8 block artifacts throughout."
        elif d.severity > 0.4:
            return "JPEG compression artifacts are present, indicating the image was saved at moderate quality."
        return "Minor JPEG compression artifacts are detectable, suggesting a reasonably high-quality save."
    elif d.name == "Multiple Re-compressions":
        return (
            "The image shows signs of being compressed, decompressed, and re-compressed multiple times "
            "- a telltale sign of being downloaded and re-uploaded across platforms."
        )
    return f"Compression-related degradation detected: {d.name}."


def _narrate_quality(d: Degradation) -> str:
    if d.name == "Noise":
        if d.severity > 0.7:
            return "Significant noise is present, possibly from a low-light capture or heavy processing."
        return "Some noise has been introduced, likely from sensor limitations or processing."
    elif d.name == "Resolution Loss / Upscaling":
        return "The image appears to have been downscaled and then upscaled, resulting in lost detail and soft edges."
    elif d.name == "Color Shift":
        return "The color balance has shifted, possibly from format conversions or platform processing that altered the color space."
    return f"Quality degradation detected: {d.name}."


def _narrate_artifact(d: Degradation) -> str:
    if d.name == "Screenshot Artifacts":
        return "The image was likely captured as a screenshot, as evidenced by solid-color borders and screen-resolution dimensions."
    elif d.name == "Watermark":
        return "A watermark overlay has been detected, suggesting the image was sourced from a stock photo service or protected content."
    return f"Visual artifacts detected: {d.name}."


def _narrate_platform(d: Degradation) -> str:
    detail = d.detail.split(".")[0] if d.detail else ""
    return (
        f"Analysis of compression patterns and dimensions suggests this image was processed "
        f"by a social media platform. {detail}."
    )


def _narrate_metadata(d: Degradation) -> str:
    if d.name == "EXIF Metadata Stripped":
        return (
            "The EXIF metadata has been stripped, which commonly happens when images are "
            "uploaded to social media platforms or processed by image editing software. "
            "Original camera information, GPS data, and timestamps have been lost."
        )
    return f"Metadata issue: {d.name}."


def _narrate_forgery(d: Degradation) -> str:
    return (
        "Copy-move manipulation has been detected - regions of the image appear to have been "
        "cloned and pasted to different locations, suggesting deliberate editing to hide or "
        "duplicate content."
    )


def _narrate_security(d: Degradation) -> str:
    return (
        "Statistical analysis of the least significant bits suggests that data may have been "
        "hidden within this image using steganographic techniques. The image may carry an "
        "embedded payload invisible to the naked eye."
    )
